name: Auto Delete Old Files

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  delete-old-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Delete files older than 2 days
        run: |
          find . -type f -not -path './.git/*' -mtime +2 -print -delete
      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "Auto-delete files older than 2 days" || exit 0
          git push
